services:
  marzban:
    image: gozargah/marzban:v0.6.0
    container_name: marzban
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/marzban:/var/lib/marzban